name: build for speeeed

on:
  workflow_dispatch:

jobs:
  baseline:
    runs-on: ubuntu-22.04

    steps:
      - name: Install OS dependencies
        run: >
          sudo apt-get install -y
          cmake
          device-tree-compiler
          git
          ninja-build
          python3
          python3-pip
          wget
          xz-utils

      - name: Install build tools
        run: |
          pip3 install wheel
          pip3 install west

      - name: Install Zephyr SDK
        run: |
          wget -q "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz"
          mkdir -p /opt/zephyr-sdk
          tar -xvf zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz -C /opt/zephyr-sdk --strip-components=1
          /opt/zephyr-sdk/setup.sh -t arm-zephyr-eabi
          rm zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz

      - name: Build with West
        run: |
          west init ~/zephyrproject
          cd ~/zephyrproject
          west update
          west zephyr-export
          pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
          cd ~/zephyrproject/zephyr
          west build -p always -b stm32_min_dev_blue samples/basic/blinky

  narrow:
    runs-on: ubuntu-22.04

    steps:
      - name: Install OS dependencies
        run: >
          sudo apt-get install -y
          cmake
          device-tree-compiler
          git
          ninja-build
          python3
          python3-pip
          wget
          xz-utils

      - name: Install build tools
        run: |
          pip3 install wheel
          pip3 install west

      - name: Install Zephyr SDK
        run: |
          wget -q "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz"
          mkdir -p /opt/zephyr-sdk
          tar -xvf zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz -C /opt/zephyr-sdk --strip-components=1
          /opt/zephyr-sdk/setup.sh -t arm-zephyr-eabi
          rm zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz

      - name: Build with West
        run: |
          west init ~/zephyrproject
          cd ~/zephyrproject
          west update --narrow
          west zephyr-export
          pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
          cd ~/zephyrproject/zephyr
          west build -p always -b stm32_min_dev_blue samples/basic/blinky

  depth1:
    runs-on: ubuntu-22.04

    steps:
      - name: Install OS dependencies
        run: >
          sudo apt-get install -y
          cmake
          device-tree-compiler
          git
          ninja-build
          python3
          python3-pip
          wget
          xz-utils

      - name: Install build tools
        run: |
          pip3 install wheel
          pip3 install west

      - name: Install Zephyr SDK
        run: |
          wget -q "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz"
          mkdir -p /opt/zephyr-sdk
          tar -xvf zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz -C /opt/zephyr-sdk --strip-components=1
          /opt/zephyr-sdk/setup.sh -t arm-zephyr-eabi
          rm zephyr-sdk-0.16.1_linux-x86_64_minimal.tar.xz

      - name: Build with West
        run: |
          west init ~/zephyrproject
          cd ~/zephyrproject
          west update -o=--depth=1
          west zephyr-export
          pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
          cd ~/zephyrproject/zephyr
          west build -p always -b stm32_min_dev_blue samples/basic/blinky